name: build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install npm dependencies    
      run: npm install
    - name: change the config
      run: echo "export const setting = {host:\"http://localhost:3030\"}" > config.js  
    - name: Run start BackEnd
      run: npm run start-be &
    - name: Run start FrontEnd
      run: npm run start-fe &
    - name: Install Playwright Browsers
      run: npx playwright install 
    - name: Run start UI test
      run: npm run test:ui

  deploy_backend:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
    - name: Deploy to production
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.BackEnd_Key }}
        api-key: ${{ secrets.Render_key }} 
    - name: Sleep for 60
      run: sleep 60    

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: deploy_backend
    steps:
    - name: Deploy to production
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.FrontEnd_Key }}
        api-key: ${{ secrets.Render_key }} 
    - name: Sleep for 60
      run: sleep 60  